### ISSUE TITLE
Committee on Calendar Bugs 

### ISSUE THREAD

**Issue by ImJustChew** [nthumodifications/courseweb#539]
- [x] - Unable to Add Events #534 
- [x] - Can't click dates in All Day selection #533 
- [x] - Unable to change end date #528 
- [x] - Cannot Remove Event #524 
- [ ] - Consecutive Events Don't Appear #524 
- [x] - Cannot Select Desired Time #524 
- [x] - Cannot Choose Tim of event #524
